#import <Foundation/Foundation.h>
#import "SWGCreateListenerParams.h"
#import "SWGDeleteEntry.h"
#import "SWGListListeners.h"
#import "SWGListenerFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGListenersApi: NSObject <SWGApi>

extern NSString* kSWGListenersApiErrorDomain;
extern NSInteger kSWGListenersApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a listener object to your account that can be used to subscribe an event.
/// Add a listener object to your account that can be used to subscribe an event. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Post Listener API with the following definition: POST https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners
///
/// @param accountId Account ID
/// @param data Account Listeners Data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGListenerFull*
-(NSURLSessionTask*) createAccountListenerWithAccountId: (NSNumber*) accountId
    data: (SWGCreateListenerParams*) data
    completionHandler: (void (^)(SWGListenerFull* output, NSError* error)) handler;


/// Delete an individual event listener.
/// Delete an individual event listener. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Delete Listener API with the following definition: DELETE https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
///
/// @param accountId Account ID
/// @param listenerId Listener ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountListenerWithAccountId: (NSNumber*) accountId
    listenerId: (NSNumber*) listenerId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Show details of an individual listener.
/// Show details of an individual event listener. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Get Listener API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
///
/// @param accountId Account ID
/// @param listenerId Listener ID
/// 
///  code:200 message:"",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGListenerFull*
-(NSURLSessionTask*) getAccountListenerWithAccountId: (NSNumber*) accountId
    listenerId: (NSNumber*) listenerId
    completionHandler: (void (^)(SWGListenerFull* output, NSError* error)) handler;


/// Get a list of listeners for an account.
/// Get a list of listeners for an account. See Account Listeners for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List Listeners API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param sortId ID sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListListeners*
-(NSURLSessionTask*) listAccountListenersWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    sortId: (NSString*) sortId
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListListeners* output, NSError* error)) handler;


/// Update the settings of an individual event listener.
/// Update the settings of an individual event listener. See Event Listeners for more detail. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Replace Listener API with the following definition: PUT https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/listeners/:listener_id
///
/// @param accountId Account ID
/// @param listenerId Listener ID
/// @param data Account Listeners Data (optional)
/// 
///  code:200 message:"",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGListenerFull*
-(NSURLSessionTask*) replaceAccountListenerWithAccountId: (NSNumber*) accountId
    listenerId: (NSNumber*) listenerId
    data: (SWGCreateListenerParams*) data
    completionHandler: (void (^)(SWGListenerFull* output, NSError* error)) handler;



@end
