#import <Foundation/Foundation.h>
#import "SWGCreateMediaParams.h"
#import "SWGDeleteEntry.h"
#import "SWGListMedia.h"
#import "SWGMediaFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGMediaApi: NSObject <SWGApi>

extern NSString* kSWGMediaApiErrorDomain;
extern NSInteger kSWGMediaApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
/// See Account Media for more info on the properties.
///
/// @param accountId Account ID
/// @param json Media extra parameters (optional)
/// @param file Media file (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) createAccountMediaFilesWithAccountId: (NSNumber*) accountId
    json: (NSString*) json
    file: (NSURL*) file
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Add a media object to your account that can be used as a greeting or hold music. Users may create a media by using the built-in Text-to-speech (TTS) facility or upload a file of their choice. (Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB)
/// See Account Media for more info on the properties.
///
/// @param accountId Account ID
/// @param data Media data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) createAccountMediaTtsWithAccountId: (NSNumber*) accountId
    data: (SWGCreateMediaParams*) data
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Delete an individual media record
/// See Account Media for more info on the properties.
///
/// @param accountId Account ID
/// @param mediaId Media ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:409 message:"Conflict"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountMediaWithAccountId: (NSNumber*) accountId
    mediaId: (NSNumber*) mediaId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Show details of an individual media recording (Greeting or Hold Music)
/// Get individual media recording
///
/// @param accountId Account ID
/// @param mediaId Media ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) getAccountMediaWithAccountId: (NSNumber*) accountId
    mediaId: (NSNumber*) mediaId
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Get a list of media recordings for an account.
/// Get a list of media recordings for an account. See Account Media for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List Media API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/media
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersName Name filter (optional)
/// @param sortId ID sorting (optional)
/// @param sortName Name sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListMedia*
-(NSURLSessionTask*) listAccountMediaWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersName: (NSArray<NSString*>*) filtersName
    sortId: (NSString*) sortId
    sortName: (NSString*) sortName
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListMedia* output, NSError* error)) handler;


/// Update a media object to your account. Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB.
/// See Account Media for more info on the properties.
///
/// @param accountId Account ID
/// @param mediaId Media ID
/// @param json Media extra parameters (optional)
/// @param file Media file (optional)
/// 
///  code:201 message:"Replaced",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) replaceAccountMediaFilesWithAccountId: (NSNumber*) accountId
    mediaId: (NSNumber*) mediaId
    json: (NSString*) json
    file: (NSURL*) file
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;


/// Update a media object to your account.
/// Update a media object to your account. Note: The maximum size for media files or JSON objects included with a POST or PUT request is 10 MB. See Account Media for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Replace Media API with the following definition: PUT https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/media/:media_id
///
/// @param accountId Account ID
/// @param mediaId Media ID
/// @param data Media data (optional)
/// 
///  code:201 message:"Replaced",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGMediaFull*
-(NSURLSessionTask*) replaceAccountMediaTtsWithAccountId: (NSNumber*) accountId
    mediaId: (NSNumber*) mediaId
    data: (SWGCreateMediaParams*) data
    completionHandler: (void (^)(SWGMediaFull* output, NSError* error)) handler;



@end
