#import <Foundation/Foundation.h>
#import "SWGDeleteEntry.h"
#import "SWGListOauthClients.h"
#import "SWGOauthClientFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGOauthclientsApi: NSObject <SWGApi>

extern NSString* kSWGOauthclientsApiErrorDomain;
extern NSInteger kSWGOauthclientsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Delete an individual OAuth client.
/// Delete an individual OAuth client. See Account OAuth Clients for more info on the properties.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:409 message:"Conflict"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountOauthClientWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Show details of an individual OAuth client.
/// Show details of an individual OAuth client. See Account OAuth Clients for more info on the properties.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGOauthClientFull*
-(NSURLSessionTask*) getAccountOauthClientWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    completionHandler: (void (^)(SWGOauthClientFull* output, NSError* error)) handler;


/// Get a list of OAuth clients for an account.
/// Get a list of OAuth clients for an account. See Account OAuth Clients for more info on the properties.
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param sortId ID sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListOauthClients*
-(NSURLSessionTask*) listAccountOauthClientsWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    sortId: (NSString*) sortId
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListOauthClients* output, NSError* error)) handler;



@end
