#import <Foundation/Foundation.h>
#import "SWGCreateRedirectUriParams.h"
#import "SWGDeleteEntry.h"
#import "SWGListOauthClientsRedirectUris.h"
#import "SWGOauthClientRedirectUriFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGOauthclientsredirecturisApi: NSObject <SWGApi>

extern NSString* kSWGOauthclientsredirecturisApiErrorDomain;
extern NSInteger kSWGOauthclientsredirecturisApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create an OAuth Client Redirect URI record.
/// Create an OAuth Client Redirect URI record.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// @param data Redirect Uri data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGOauthClientRedirectUriFull*
-(NSURLSessionTask*) createAccountOauthClientsRedirectUriWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    data: (SWGCreateRedirectUriParams*) data
    completionHandler: (void (^)(SWGOauthClientRedirectUriFull* output, NSError* error)) handler;


/// Delete an OAuth Client Redirect URI record.
/// Delete an OAuth Client Redirect URI record.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// @param uriId Redirect URI ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:409 message:"Conflict"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountOauthClientsRedirectUriWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    uriId: (NSNumber*) uriId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Get details of an OAuth Client Redirect URI record.
/// Get details of an OAuth Client Redirect URI record.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// @param uriId Redirect URI ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGOauthClientRedirectUriFull*
-(NSURLSessionTask*) getAccountOauthClientsRedirectUriWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    uriId: (NSNumber*) uriId
    completionHandler: (void (^)(SWGOauthClientRedirectUriFull* output, NSError* error)) handler;


/// Get a list of OAuth Client Redirect URIs for an account.
/// Get a list of OAuth Client Redirect URIs for an account.
///
/// @param accountId Account ID
/// @param clientId Client ID
/// @param filtersId ID filter (optional)
/// @param sortId ID sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListOauthClientsRedirectUris*
-(NSURLSessionTask*) listAccountOauthClientsRedirectUrisWithAccountId: (NSNumber*) accountId
    clientId: (NSNumber*) clientId
    filtersId: (NSArray<NSString*>*) filtersId
    sortId: (NSString*) sortId
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListOauthClientsRedirectUris* output, NSError* error)) handler;



@end
