#import <Foundation/Foundation.h>
#import "SWGCreateRouteParams.h"
#import "SWGDeleteEntry.h"
#import "SWGListRoutes.h"
#import "SWGRouteFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGRoutesApi: NSObject <SWGApi>

extern NSString* kSWGRoutesApiErrorDomain;
extern NSInteger kSWGRoutesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a new route to the account.
/// Add a new route to the account. See Intro to Routes for more info on the properties.
///
/// @param accountId Account ID
/// @param data Route data (optional)
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGRouteFull*
-(NSURLSessionTask*) createRouteWithAccountId: (NSNumber*) accountId
    data: (SWGCreateRouteParams*) data
    completionHandler: (void (^)(SWGRouteFull* output, NSError* error)) handler;


/// Delete a route from the account.
/// Delete a route from the account. See Intro to Routes for more info on the properties.
///
/// @param accountId Account ID
/// @param routeId Route ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:409 message:"Conflict"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountRouteWithAccountId: (NSNumber*) accountId
    routeId: (NSNumber*) routeId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Show details of an individual route.
/// Show details of an individual route. See Intro to Routes for more info on the properties.
///
/// @param accountId Account ID
/// @param routeId Route ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGRouteFull*
-(NSURLSessionTask*) getAccountRouteWithAccountId: (NSNumber*) accountId
    routeId: (NSNumber*) routeId
    completionHandler: (void (^)(SWGRouteFull* output, NSError* error)) handler;


/// Get a list of routes for an account.
/// Get a list of routes for an account. See Intro to Routes for more info on the properties.
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersName Name filter (optional)
/// @param sortId ID sorting (optional)
/// @param sortName Name sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListRoutes*
-(NSURLSessionTask*) listAccountRoutesWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersName: (NSArray<NSString*>*) filtersName
    sortId: (NSString*) sortId
    sortName: (NSString*) sortName
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListRoutes* output, NSError* error)) handler;


/// Update the information of a route.
/// Update the information of a route. See Intro to Routes for more info on the properties.
///
/// @param accountId Account ID
/// @param routeId Route ID
/// @param data Route data (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGRouteFull*
-(NSURLSessionTask*) replaceAccountRouteWithAccountId: (NSNumber*) accountId
    routeId: (NSNumber*) routeId
    data: (SWGCreateRouteParams*) data
    completionHandler: (void (^)(SWGRouteFull* output, NSError* error)) handler;



@end
