#import <Foundation/Foundation.h>
#import "SWGCreateSmsParams.h"
#import "SWGListSms.h"
#import "SWGPatchSmsParams.h"
#import "SWGSmsFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSmsApi: NSObject <SWGApi>

extern NSString* kSWGSmsApiErrorDomain;
extern NSInteger kSWGSmsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Send a SMS to one or a group of recipients.
/// Send a SMS to one or a group of recipients. For details on the input fields, see Intro to SMS. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Create SMS API with the following definition: POST https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms
///
/// @param accountId Account ID
/// @param data SMS data
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data",
///  code:429 message:"Rate Limit Reached"
///
/// @return SWGSmsFull*
-(NSURLSessionTask*) createAccountSmsWithAccountId: (NSNumber*) accountId
    data: (SWGCreateSmsParams*) data
    completionHandler: (void (^)(SWGSmsFull* output, NSError* error)) handler;


/// This service shows the details of an individual SMS.
/// This service shows the details of an individual SMS. See Intro to SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Get SMS API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms/:sms_id
///
/// @param accountId Account ID
/// @param smsId SMS ID
/// 
///  code:200 message:"",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGSmsFull*
-(NSURLSessionTask*) getAccountSmsWithAccountId: (NSNumber*) accountId
    smsId: (NSString*) smsId
    completionHandler: (void (^)(SWGSmsFull* output, NSError* error)) handler;


/// Get a list of SMS messages for an account.
/// Get a list of SMS messages for an account. See Intro to SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level List SMS API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersFrom Caller ID filter (optional)
/// @param filtersTo Callee ID filter, the E.164 phone number to send the SMS TO. Note you must encode the + as %2B (optional)
/// @param filtersDirection Direction filter (optional)
/// @param filtersExtension Extension filter (optional)
/// @param filtersCreatedAt Date string representing the UTC time that sms was created (optional)
/// @param sortId ID sorting (optional)
/// @param sortCreatedAt Sort by created time of message (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListSms*
-(NSURLSessionTask*) listAccountSmsWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersFrom: (NSString*) filtersFrom
    filtersTo: (NSString*) filtersTo
    filtersDirection: (NSString*) filtersDirection
    filtersExtension: (NSArray<NSString*>*) filtersExtension
    filtersCreatedAt: (NSString*) filtersCreatedAt
    sortId: (NSString*) sortId
    sortCreatedAt: (NSString*) sortCreatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListSms* output, NSError* error)) handler;


/// Update the is_new parameter in a sms record.
/// Update the is_new parameter in a sms record. See Account SMS for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Extension level Patch SMS API with the following definition: PATCH https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/sms/:sms_id
///
/// @param accountId Account ID
/// @param smsId SMS ID
/// @param data Sms data (optional)
/// 
///  code:200 message:"",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGSmsFull*
-(NSURLSessionTask*) patchAccountSmsWithAccountId: (NSNumber*) accountId
    smsId: (NSString*) smsId
    data: (SWGPatchSmsParams*) data
    completionHandler: (void (^)(SWGSmsFull* output, NSError* error)) handler;



@end
