#import <Foundation/Foundation.h>
#import "SWGCreatePricingParams.h"
#import "SWGDeleteEntry.h"
#import "SWGListPricings.h"
#import "SWGPricingFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGSubaccountpricingApi: NSObject <SWGApi>

extern NSString* kSWGSubaccountpricingApiErrorDomain;
extern NSInteger kSWGSubaccountpricingApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Add a pricing plan to a subaccount.
/// Add a pricing plan to a subaccount. See Account Subaccount Pricing for more info on the properties.
///
/// @param accountId Account ID
/// @param subaccountId Subaccount ID
/// @param data Subaccount pricing data
/// 
///  code:201 message:"Created",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:422 message:"Invalid Data"
///
/// @return SWGPricingFull*
-(NSURLSessionTask*) createAccountSubaccountPricingWithAccountId: (NSNumber*) accountId
    subaccountId: (NSNumber*) subaccountId
    data: (SWGCreatePricingParams*) data
    completionHandler: (void (^)(SWGPricingFull* output, NSError* error)) handler;


/// Delete a pricing plan from a subaccount.
/// Delete a pricing plan from a subaccount. See Account Subaccount Pricing for more info on the properties.
///
/// @param accountId Account ID
/// @param subaccountId Subaccount ID
/// @param pricingId Pricing Object ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:409 message:"Conflict"
///
/// @return SWGDeleteEntry*
-(NSURLSessionTask*) deleteAccountSubaccountPricingWithAccountId: (NSNumber*) accountId
    subaccountId: (NSNumber*) subaccountId
    pricingId: (NSNumber*) pricingId
    completionHandler: (void (^)(SWGDeleteEntry* output, NSError* error)) handler;


/// Get the details of a pricing plan for a subaccount.
/// Get the details of a pricing plan for a subaccount. See Account Subaccount Pricing for more info on the properties.
///
/// @param accountId Account ID
/// @param subaccountId Subaccount ID
/// @param pricingId Pricing Object ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGPricingFull*
-(NSURLSessionTask*) getAccountSubaccountPricingWithAccountId: (NSNumber*) accountId
    subaccountId: (NSNumber*) subaccountId
    pricingId: (NSNumber*) pricingId
    completionHandler: (void (^)(SWGPricingFull* output, NSError* error)) handler;


/// Get a list of pricing plans for a subaccount.
/// Get a list of pricing plans for a subaccount. See Account Subaccount Pricing for more info on the properties.
///
/// @param accountId Account ID
/// @param subaccountId Subaccount ID
/// @param filtersId ID filter (optional)
/// @param sortId ID sorting (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListPricings*
-(NSURLSessionTask*) listAccountSubaccountPricingWithAccountId: (NSNumber*) accountId
    subaccountId: (NSNumber*) subaccountId
    filtersId: (NSArray<NSString*>*) filtersId
    sortId: (NSString*) sortId
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListPricings* output, NSError* error)) handler;



@end
