#import <Foundation/Foundation.h>
#import "SWGListVoicemail.h"
#import "SWGPatchVoicemailParams.h"
#import "SWGVoicemailFull.h"
#import "SWGApi.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGVoicemailApi: NSObject <SWGApi>

extern NSString* kSWGVoicemailApiErrorDomain;
extern NSInteger kSWGVoicemailApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// This service shows the details of an individual voicemail.
/// This service shows the details of an individual voicemail. See Intro to Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Get Voicemail API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail/:voicemail_id
///
/// @param accountId Account ID
/// @param voicemailId Voicemail ID
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGVoicemailFull*
-(NSURLSessionTask*) getAccountVoicemailWithAccountId: (NSNumber*) accountId
    voicemailId: (NSString*) voicemailId
    completionHandler: (void (^)(SWGVoicemailFull* output, NSError* error)) handler;


/// Get a list of voicemail messages for an account.
/// Get a list of voicemail messages for an account. See Intro to Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the List Voicemail API with the following definition: GET https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail
///
/// @param accountId Account ID
/// @param filtersId ID filter (optional)
/// @param filtersFrom Caller ID filter (optional)
/// @param filtersTo Callee ID filter, the E.164 phone number to send the SMS TO. Note you must encode the + as %2B (optional)
/// @param filtersIsNew  (optional)
/// @param filtersCreatedAt Date string representing the UTC time that sms was created (optional)
/// @param filtersExtension Extension filter (optional)
/// @param sortId ID sorting (optional)
/// @param sortCreatedAt Sort by the UTC time that voicemail was created (optional)
/// @param limit Max results (optional)
/// @param offset Results to skip (optional)
/// @param fields Field set (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden"
///
/// @return SWGListVoicemail*
-(NSURLSessionTask*) listAccountVoicemailWithAccountId: (NSNumber*) accountId
    filtersId: (NSArray<NSString*>*) filtersId
    filtersFrom: (NSString*) filtersFrom
    filtersTo: (NSString*) filtersTo
    filtersIsNew: (NSNumber*) filtersIsNew
    filtersCreatedAt: (NSString*) filtersCreatedAt
    filtersExtension: (NSArray<NSString*>*) filtersExtension
    sortId: (NSString*) sortId
    sortCreatedAt: (NSString*) sortCreatedAt
    limit: (NSNumber*) limit
    offset: (NSNumber*) offset
    fields: (NSString*) fields
    completionHandler: (void (^)(SWGListVoicemail* output, NSError* error)) handler;


/// Update the is_new parameter in a voicemail record.
/// Update the is_new parameter in a voicemail record. See Account Voicemail for more info on the properties. Note: This API is for users with Account Owner scope access token. Users with Extension User scope token should invoke the Patch Voicemail API with the following definition: PATCH https://api.phone.com/v4/accounts/:account_id/extensions/:extension_id/voicemail/:voicemail_id
///
/// @param accountId Account ID
/// @param voicemailId Voicemail ID
/// @param data Payment data (optional)
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized access",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found",
///  code:422 message:"Invalid Data"
///
/// @return SWGVoicemailFull*
-(NSURLSessionTask*) patchAccountVoicemailWithAccountId: (NSNumber*) accountId
    voicemailId: (NSString*) voicemailId
    data: (SWGPatchVoicemailParams*) data
    completionHandler: (void (^)(SWGVoicemailFull* output, NSError* error)) handler;



@end
