#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCreateOauthParams
@end

@interface SWGCreateOauthParams : SWGObject

/* authorization_code, client_credentials, password or refresh_token [optional]
 */
@property(nonatomic) NSString* grantType;
/* Client ID [optional]
 */
@property(nonatomic) NSString* clientId;
/* Client Secret Key [optional]
 */
@property(nonatomic) NSString* clientSecret;
/* Authorization Code created via the /oauth/authorization API [optional]
 */
@property(nonatomic) NSString* code;
/* The redirect URI where user enters authentication information [optional]
 */
@property(nonatomic) NSString* redirectUri;
/* account-owner, extension-user and/or methods:ALL, separated by space (%20) [optional]
 */
@property(nonatomic) NSString* scope;
/* User name [optional]
 */
@property(nonatomic) NSString* username;
/* Password [optional]
 */
@property(nonatomic) NSString* password;
/* Refresh token [optional]
 */
@property(nonatomic) NSString* refreshToken;

@end
