#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCreatePaymentParams
@end

@interface SWGCreatePaymentParams : SWGObject

/* Name of payment method [optional]
 */
@property(nonatomic) NSString* nickname;
/* primary, onfile or hidden [optional]
 */
@property(nonatomic) NSString* status;
/* Credit Card Type [optional]
 */
@property(nonatomic) NSString* type;
/* Credit Card Token. Token is obtained by entering credit card info via the Credit Card Entry Form [optional]
 */
@property(nonatomic) NSString* ccToken;

@end
