#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGContactResponse.h"


@protocol SWGCreateSubaccountParams
@end

@interface SWGCreateSubaccountParams : SWGObject

/* Sub account password 
 */
@property(nonatomic) NSString* username;
/* Sub account password 
 */
@property(nonatomic) NSString* password;
/* Contact Object. See below for details. [optional]
 */
@property(nonatomic) SWGContactResponse* contact;
/* Contact Object for billing purposes. See below for details. [optional]
 */
@property(nonatomic) SWGContactResponse* billingContact;

@end
