#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGAddress.h"


@protocol SWGContactResponse
@end

@interface SWGContactResponse : SWGObject

/* Contact name [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) SWGAddress* address;
/* Primary email address. Required. [optional]
 */
@property(nonatomic) NSString* primaryEmail;
/* Alternate email address [optional]
 */
@property(nonatomic) NSString* alternateEmail;
/* Company name [optional]
 */
@property(nonatomic) NSString* company;
/* Phone number. Required. [optional]
 */
@property(nonatomic) NSString* phone;
/* Fax number [optional]
 */
@property(nonatomic) NSString* fax;

@end
