#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGCreatePricingParams
@end

@interface SWGCreatePricingParams : SWGObject

/* Pricing plan code [optional]
 */
@property(nonatomic) NSNumber* pricingId;
/* Reason this pricing plan is added to the subaccount [optional]
 */
@property(nonatomic) NSString* reason;
/* Pricing plan expiration time in UNIX format. Disregard or set it to null for plan which never expires [optional]
 */
@property(nonatomic) NSNumber* expireDate;

@end
