#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCallNotifications.h"
#import "SWGVoicemailInput.h"


@protocol SWGCreateExtensionParams
@end

@interface SWGCreateExtensionParams : SWGObject


@property(nonatomic) SWGVoicemailInput* voicemail;

@property(nonatomic) SWGCallNotifications* callNotifications;
/* Caller ID [optional]
 */
@property(nonatomic) NSString* callerId;
/* Extension type [optional]
 */
@property(nonatomic) NSString* usageType;
/* Extension number (auto-generated if empty) [optional]
 */
@property(nonatomic) NSNumber* extension;
/* Include in dial-by-name directory [optional]
 */
@property(nonatomic) NSString* includeInDirectory;
/* Name (auto-generated if empty) [optional]
 */
@property(nonatomic) NSString* name;
/* Contact name [optional]
 */
@property(nonatomic) NSString* fullName;
/* Timezone [optional]
 */
@property(nonatomic) NSString* timezone;
/* Recording lookup object [optional]
 */
@property(nonatomic) NSObject* nameGreeting;
/* Local area code [optional]
 */
@property(nonatomic) NSString* localAreaCode;
/* Enable outgoing calls [optional]
 */
@property(nonatomic) NSString* enableOutboundCalls;
/* Enable Call Waiting [optional]
 */
@property(nonatomic) NSString* enableCallWaiting;

@end
