#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCallbackObject.h"


@protocol SWGCreateListenerParams
@end

@interface SWGCreateListenerParams : SWGObject

/* Type of listener. Must be 'callback' [optional]
 */
@property(nonatomic) NSString* type;
/* Type of event to subscribe. 'call.new', 'call.update', 'call.complete' [optional]
 */
@property(nonatomic) NSString* eventType;
/* Array of Callback Objects. [optional]
 */
@property(nonatomic) NSArray<SWGCallbackObject>* callbacks;

@end
