#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGFromObject
@end

@interface SWGFromObject : SWGObject

/* The caller phone number [optional]
 */
@property(nonatomic) NSString* number;
/* The name / caller ID of the caller [optional]
 */
@property(nonatomic) NSString* name;
/* The city where the caller is from [optional]
 */
@property(nonatomic) NSString* city;
/* The state where the caller is from [optional]
 */
@property(nonatomic) NSString* state;

@end
