#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGListenerFull
@end

@interface SWGListenerFull : SWGObject

/* Integer ID. Read-only. [optional]
 */
@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSNumber* voipId;
/* Type of listener: callback [optional]
 */
@property(nonatomic) NSString* type;
/* Type of event subscribed by the listener: call.new, call.update, call.complete, call.log, sms.in, sms.out [optional]
 */
@property(nonatomic) NSString* eventType;
/* Array of Callback Object [optional]
 */
@property(nonatomic) NSArray<NSObject*>* callbacks;

@property(nonatomic) NSNumber* updatedAt;

@property(nonatomic) NSNumber* createdAt;

@end
