#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGFilterIdArray.h"
#import "SWGPricingFull.h"
#import "SWGSortId.h"


@protocol SWGListPricings
@end

@interface SWGListPricings : SWGObject


@property(nonatomic) SWGFilterIdArray* filters;

@property(nonatomic) SWGSortId* sort;

@property(nonatomic) NSNumber* total;

@property(nonatomic) NSNumber* offset;

@property(nonatomic) NSNumber* limit;

@property(nonatomic) NSArray<SWGPricingFull>* items;

@end
