#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGOauthClientFull
@end

@interface SWGOauthClientFull : SWGObject

/* Client ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Name of Client [optional]
 */
@property(nonatomic) NSString* clientName;

@end
