#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGPaymentSummary
@end

@interface SWGPaymentSummary : SWGObject

/* Payment Method ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* API Account ID [optional]
 */
@property(nonatomic) NSNumber* voipId;
/* 'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card; [optional]
 */
@property(nonatomic) NSString* status;
/* Name of Card [optional]
 */
@property(nonatomic) NSString* nickname;
/* 'cc' for credit card [optional]
 */
@property(nonatomic) NSString* type;
/* Time payment record is created [optional]
 */
@property(nonatomic) NSNumber* createdAt;

@end
