#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGContactResponse.h"


@protocol SWGPaymentFull
@end

@interface SWGPaymentFull : SWGObject

/* Payment Method ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* API Account ID [optional]
 */
@property(nonatomic) NSNumber* voipId;
/* 'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card; [optional]
 */
@property(nonatomic) NSString* status;
/* Name of Card [optional]
 */
@property(nonatomic) NSString* nickname;
/* 'cc' for credit card [optional]
 */
@property(nonatomic) NSString* type;
/* Time payment record is created [optional]
 */
@property(nonatomic) NSNumber* createdAt;
/* Detail of contact person [optional]
 */
@property(nonatomic) SWGContactResponse* contact;
/* Number of times the payment method was declined [optional]
 */
@property(nonatomic) NSNumber* declineCount;
/* Next billing date [optional]
 */
@property(nonatomic) NSNumber* nextChargeDate;
/* Last time the payment method was updated [optional]
 */
@property(nonatomic) NSNumber* updatedAt;
/* Encrypted credit card token to be used for billing [optional]
 */
@property(nonatomic) NSString* ccToken;
/* Credit card number partially masked with xxxxxxxx [optional]
 */
@property(nonatomic) NSString* ccNumber;
/* Credit card expiration date [optional]
 */
@property(nonatomic) NSString* ccExp;

@end
