#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGPricingObject
@end

@interface SWGPricingObject : SWGObject

/* Pricing code / ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* Name of pricing plan [optional]
 */
@property(nonatomic) NSString* name;

@end
