#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCallNotifications.h"
#import "SWGCallerIdPhoneNumber.h"
#import "SWGSmsForwardingParams.h"


@protocol SWGReplacePhoneNumberParams
@end

@interface SWGReplacePhoneNumberParams : SWGObject

/* Route lookup object [optional]
 */
@property(nonatomic) NSObject* route;
/* Phone Name [optional]
 */
@property(nonatomic) NSString* name;
/* Block incoming calls [optional]
 */
@property(nonatomic) NSString* blockIncoming;
/* Block anonymous calls [optional]
 */
@property(nonatomic) NSString* blockAnonymous;

@property(nonatomic) SWGCallerIdPhoneNumber* callerId;

@property(nonatomic) SWGSmsForwardingParams* smsForwarding;
/* Pool lookup object [optional]
 */
@property(nonatomic) NSObject* poolItem;

@property(nonatomic) SWGCallNotifications* callNotifications;

@end
