#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCallNotifications.h"
#import "SWGVoicemailInput.h"


@protocol SWGReplaceExtensionParams
@end

@interface SWGReplaceExtensionParams : SWGObject


@property(nonatomic) SWGVoicemailInput* voicemail;

@property(nonatomic) SWGCallNotifications* callNotifications;
/* Recording lookup object [optional]
 */
@property(nonatomic) NSObject* nameGreeting;
/* Name (required) [optional]
 */
@property(nonatomic) NSString* name;
/* Timezone [optional]
 */
@property(nonatomic) NSString* timezone;
/* Include in dial-by-name directory [optional]
 */
@property(nonatomic) NSString* includeInDirectory;
/* Extension number (required) [optional]
 */
@property(nonatomic) NSNumber* extension;
/* Enable outgoing calls [optional]
 */
@property(nonatomic) NSString* enableOutboundCalls;
/* Extension type [optional]
 */
@property(nonatomic) NSString* usageType;
/* Contact name [optional]
 */
@property(nonatomic) NSString* fullName;
/* Enable Call Waiting [optional]
 */
@property(nonatomic) NSString* enableCallWaiting;
/* Caller ID [optional]
 */
@property(nonatomic) NSString* callerId;
/* Local area code [optional]
 */
@property(nonatomic) NSString* localAreaCode;
/* Route object lookup (must belong to this extension) [optional]
 */
@property(nonatomic) NSString* route;

@end
