#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGCallNotifications.h"
#import "SWGCallerIdPhoneNumber.h"
#import "SWGSmsForwardingParams.h"


@protocol SWGReplacePhoneNumberParams
@end

@interface SWGReplacePhoneNumberParams : SWGObject

/* Route lookup object [optional]
 */
@property(nonatomic) NSObject* route;
/* Phone Name [optional]
 */
@property(nonatomic) NSString* name;
/* Block incoming calls [optional]
 */
@property(nonatomic) NSNumber* blockIncoming;
/* Block anonymous calls [optional]
 */
@property(nonatomic) NSNumber* blockAnonymous;
/* Caller ID object [optional]
 */
@property(nonatomic) SWGCallerIdPhoneNumber* callerId;
/* SMS Forwarding Object, or NULL [optional]
 */
@property(nonatomic) SWGSmsForwardingParams* smsForwarding;
/* Pool lookup object [optional]
 */
@property(nonatomic) NSObject* poolItem;
/* Call Notifications object [optional]
 */
@property(nonatomic) SWGCallNotifications* callNotifications;

@end
