#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol SWGRedirectUriFull
@end

@interface SWGRedirectUriFull : SWGObject

/* Redirect URI ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* The Uniform Resource Identifier is a string used to identify the path to be redirected [optional]
 */
@property(nonatomic) NSString* uri;
/* redirect [optional]
 */
@property(nonatomic) NSString* type;

@end
