#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Phone.com API
* This is a Phone.com api Swagger definition
*
* OpenAPI spec version: 1.0.0
* Contact: apisupport@phone.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGExtensionSummary.h"
#import "SWGFromObject.h"


@protocol SWGVoicemailFull
@end

@interface SWGVoicemailFull : SWGObject

/* Unique Voicemail ID. Read-only. [optional]
 */
@property(nonatomic) NSString* _id;
/* Name. Required. [optional]
 */
@property(nonatomic) NSString* downloadUrl;
/* Extension where the voicemail is saved into. [optional]
 */
@property(nonatomic) SWGExtensionSummary* extension;
/* The caller's information [optional]
 */
@property(nonatomic) SWGFromObject* from;
/* The phone number where the caller is calling [optional]
 */
@property(nonatomic) NSString* to;
/* True when Voicemail is new; False when Voicemail has been listened [optional]
 */
@property(nonatomic) NSNumber* isNew;
/* Date string representing the UTC time that the object was created in the Phone.com API system. [optional]
 */
@property(nonatomic) NSNumber* createdAt;
/* Folder name where voicemail is saved [optional]
 */
@property(nonatomic) NSString* folder;
/* Length of voicemail in seconds [optional]
 */
@property(nonatomic) NSNumber* duration;

@end
